"""Se añade la columna ciudad

Revision ID: 39ae2503f739
Revises: 
Create Date: 2024-11-07 19:11:14.342921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ae2503f739'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('puntaje_por_labor', sa.Integer(), nullable=False),
    sa.Column('puntaje_global', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('id_servicio', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_table('usuario_servicio',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id_servicio'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'servicio_id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sa.String(), nullable=False, server_default='Desconocido'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('ciudad')

    op.drop_table('usuario_servicio')
    op.drop_table('calificacion')
    # ### end Alembic commands ###
