"""Crear tabla aditional_services

Revision ID: 00d08247254b
Revises: a4d1d0ae1598
Create Date: 2025-03-17 19:28:28.666216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d08247254b'
down_revision = 'a4d1d0ae1598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aditional_services',
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('nombre_servicio', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_service')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aditional_services')
    # ### end Alembic commands ###
