"""Add columns for contratante and contratado comments

Revision ID: 3d6241ee3f25
Revises: 40a53d87b62b
Create Date: 2025-03-16 14:26:40.346049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6241ee3f25'
down_revision = '40a53d87b62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentary_hired_employer', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('comentary_employer_hired', sa.String(), nullable=True))
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('comentary_employer_hired')
        batch_op.drop_column('comentary_hired_employer')

    # ### end Alembic commands ###
