"""Agregar columna id_contratado al modelo Servicio

Revision ID: 40a53d87b62b
Revises: 8a1664255e2e
Create Date: 2025-03-15 18:21:31.071584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a53d87b62b'
down_revision = '8a1664255e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_contratado', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['id_contratado'], ['id_usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_contratado')

    # ### end Alembic commands ###
