"""Añadir columna 'active' a la tabla usuario

Revision ID: 5547a6430997
Revises: 3d6241ee3f25
Create Date: 2025-03-16 20:39:55.430770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5547a6430997'
down_revision = '3d6241ee3f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
