"""Registrar modelo Calificacion

Revision ID: 76dd83e044fb
Revises: 
Create Date: 2025-03-15 15:49:15.370646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dd83e044fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('calificacion_recived_contratante1', sa.Integer(), nullable=True),
    sa.Column('calificacion_recived_contratante2', sa.Integer(), nullable=True),
    sa.Column('calificacion_recived_contratante3', sa.Integer(), nullable=True),
    sa.Column('calificacion_recived_contratado1', sa.Integer(), nullable=True),
    sa.Column('calificacion_recived_contratado2', sa.Integer(), nullable=True),
    sa.Column('calificacion_recived_contratado3', sa.Integer(), nullable=True),
    sa.Column('puntaje_por_labor', sa.Integer(), nullable=True),
    sa.Column('puntaje_global', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id_servicio'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calificacion')
    # ### end Alembic commands ###
