"""Agregar columnas aditional_service y service_active al modelo servicio

Revision ID: 9dd6479a393f
Revises: e9510e1e415c
Create Date: 2025-03-17 11:48:12.276864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd6479a393f'
down_revision = 'e9510e1e415c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditional_service', sa.String(length=234), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_column('aditional_service')

    # ### end Alembic commands ###
