"""Agregar relación calificaciones al modelo Usuario

Revision ID: be54cb1e93e7
Revises: d709cc6f34a3
Create Date: 2025-03-15 16:33:16.896959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be54cb1e93e7'
down_revision = 'd709cc6f34a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('questions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
