"""Añadir modelos Etapa, Foto, Audio y Video

Revision ID: d53ed8ea407d
Revises: 00d08247254b
Create Date: 2025-03-25 13:56:33.564977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53ed8ea407d'
down_revision = '00d08247254b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapa',
    sa.Column('id_etapa', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id_servicio'], ),
    sa.PrimaryKeyConstraint('id_etapa')
    )
    op.create_table('audio',
    sa.Column('id_audio', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapa.id_etapa'], ),
    sa.PrimaryKeyConstraint('id_audio')
    )
    op.create_table('foto',
    sa.Column('id_foto', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapa.id_etapa'], ),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_table('video',
    sa.Column('id_video', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapa.id_etapa'], ),
    sa.PrimaryKeyConstraint('id_video')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('foto')
    op.drop_table('audio')
    op.drop_table('etapa')
    # ### end Alembic commands ###
