"""Corregir esquema de la tabla Calificacion

Revision ID: d709cc6f34a3
Revises: 76dd83e044fb
Create Date: 2025-03-15 16:03:26.544889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd709cc6f34a3'
down_revision = '76dd83e044fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.drop_constraint('calificacion_usuario_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('calificacion_servicio_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'servicio', ['servicio_id'], ['id_servicio'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('calificacion_servicio_id_fkey', 'servicio', ['servicio_id'], ['id_servicio'])
        batch_op.create_foreign_key('calificacion_usuario_id_fkey', 'usuario', ['usuario_id'], ['id_usuario'])

    # ### end Alembic commands ###
