"""Agregar columnas aditional_service y service_active al modelo servicio

Revision ID: e9510e1e415c
Revises: ea5a3966491f
Create Date: 2025-03-17 11:46:43.390415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9510e1e415c'
down_revision = 'ea5a3966491f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_column('service_active')

    # ### end Alembic commands ###
